### ISSUE TITLE
npm run asset-server throw an error

### ISSUE THREAD

**Issue by lostdalek** [Kflash/trolly#11]
Hi!
I've got the following error in config/environment.js when I run ```npm run asset-server```:
```
config/environment.js:46
var IS_PROD = (0, _lodash.any)([NODE_ENV === 'production', ENVIRONMENT === 'prod', ENVIRONMENT === 'production']);
                              ^

TypeError: (0 , _lodash.any) is not a function
    at Object.<anonymous> (environment.js:36:15)
    at Module._compile (module.js:435:26)
    at loader (/Users/.../node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/.../node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/.../config/webpack/webpack.hot.assets.config.js:6:21)
    at Module._compile (module.js:435:26)
```

not sure about ```any``` ? seems not to be part of lodash, it's undefined:
```
import {
    any, defaults
}
from 'lodash';
```

**Comment by Kflash** [comment]
@lostdalek Any have been removed from lodash v. 4 it seems. I will fix this soon as I got some time, or you can send a PR? A workaround for now would be to use a lodash 3.x
